name: Vue.js build 
on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - 
      name: Login to Gitgub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker images
      run: | 
          docker build . --tag ghcr.io/int222-26-42-45/frontend
          docker images
    - name: push docker images to registry
      run: |
          docker push ghcr.io/int222-26-42-45/frontend
